livekit:
  rtc:
    use_external_ip: false
  keys:
    cntikey: cnti-test-only-secret-with-enough-length
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi
